# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fluff' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fluff
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
 
  target 'fluff-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    #pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  end

  target 'fluffTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
      puts "Deleting React from project #{target.inspect}."
    end
  end
end
