repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        exclude: "^firebase/(dartangular|public)/.*"
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: "master"
    hooks:
      - id: flutter-format
