# Build config for angulardart and teamsfuse
image: node:6.9.4

definitions:
  caches:
    dart: ~/firebase/dartangular/.packages
    dartbuild: ~/firebase/dartangular/build
    firebasenode: ~/firebase/funcitons/node_modules
  services:
    firestore:
      image: jdlk7/firestore-emulator
      memory: 512

pipelines:
  default:
    - step:
        caches:
          - firebasenode
          - node
        name: Firebase functions deploy and build
        services:
          - firestore
        image: node
        script: # Modify the commands below to build your repository.
          - cd firebase/functions
          - npm update
          - npm install -g firebase-tools
          - npm install -g @google-cloud/functions-emulator
          - npm test
          # - firebase deploy --token="1/AbUh26_WYBfWEJJLlJaXXCGwTRFGChXTRh_tvRWQTD0LQp8QLs0D36IInl9U6euQ" --only functions,firestore,storage
          - cd ..
          - pipe: atlassian/firebase-deploy:0.2.0
            variables:
              FIREBASE_TOKEN: '1/AbUh26_WYBfWEJJLlJaXXCGwTRFGChXTRh_tvRWQTD0LQp8QLs0D36IInl9U6euQ'
              #PROJECT_ID: 'Teamsfuse'
              MESSAGE: 'Deploying TeamsFuse functions'
              EXTRA_ARGS: '--only functions,firestore'
              DEBUG: 'false'
    - step:
       caches:
         - dart
       image: google/dart
       name: Angular Dart build and deploy
       script:
         - cd firebase/dartangular
         - pub global activate webdev
         - pub global activate stagehand
         - pub get
         - webdev build --release
         - cp -rf build/* ../public
         - cd ..
         - pipe: atlassian/firebase-deploy:0.2.0
           variables:
             FIREBASE_TOKEN: '1/AbUh26_WYBfWEJJLlJaXXCGwTRFGChXTRh_tvRWQTD0LQp8QLs0D36IInl9U6euQ'
             #PROJECT_ID: 'teamsfuse'
             MESSAGE: 'Deploying Teamsfuse hosting'
             EXTRA_ARGS: '--only hosting'
             DEBUG: 'false'
