# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

definitions:
  caches:
    dart: ~/firebase/dartangular/.packages
    firebasenode: ~/firebase/funcitons/node_modules
  services:
    firestore:
      image: jdlk7/firestore-emulator
      memory: 512

pipelines:
  default:
    - step:
        caches:
          - firebasenode
          - node
        services:
          - firestore
        image: node
        script: # Modify the commands below to build your repository.
          - cd firebase/functions
          - npm update
          - npm install -g firebase-tools
          - npm install -g @google-cloud/functions-emulator
          - npm test
          - pipe: atlassian/firebase-deploy:0.2.0
          - firebase deploy --token="1/AbUh26_WYBfWEJJLlJaXXCGwTRFGChXTRh_tvRWQTD0LQp8QLs0D36IInl9U6euQ" --only functions
           # variables:
           #   FIREBASE_TOKEN: '1/AbUh26_WYBfWEJJLlJaXXCGwTRFGChXTRh_tvRWQTD0LQp8QLs0D36IInl9U6euQ'
           #   PROJECT_ID: 'Teamsfuse'
           #   MESSAGE: 'Deploying TeamsFuse functions'
           #   EXTRA_ARGS: '--only functions'
           #   DEBUG: 'false'
    - step:
       caches:
         - dart
       image: google/dart
       name: Angular Dart build
       script:
         - cd firebase/dartangular
         - pub global activate webdev
         - pub packages get
         - webdev build --release
              
