# Bild flutter_fuse for android in the cloud.

steps:
  - name: 'ubuntu'
    args: ['bash', '-c', 'date -u +%Y%m%dT%H%M_$SHORT_SHA > _TAG']

  - name: 'gcr.io/teamsfuse/flutter'
    dir: 'flutter_fuse'
    args: ['packages', 'get']

  - name: 'gcr.io/teamsfuse/flutter'
    dir: 'flutter_fuse'
    args: ['build', 'apk']

  # push apk into gcs
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'flutter_fuse'
    args: ['cp', 'flutter_fuse/build/app/outputs/apk/release/app-release.apk', 'gs://flutter_fuse_release/flutter_fuse_$(cat _TAG).apk']