#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/david/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/david/development/mobile/flutter_fuse"
export "FLUTTER_TARGET=/Users/david/development/mobile/flutter_fuse/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/david/development/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.8.8"
export "FLUTTER_BUILD_NUMBER=0.8.8"
export "DART_DEFINES='SENTRY_URL%3D%22https%3A%2F%2F5691b440eb64430d9ba2917166fa17a1%3A7978cf6a0a5a4f7ab7702a51f524620a%40sentry.io%2F1200691%22',flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
