analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore
  exclude:
    - flutter/**
    - lib/api/*.dart
    - lib/i10n/*.dart

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - always_specify_types
    - prefer_collection_literals
    - prefer_const_literals_to_create_immutables
    - prefer_initializing_formals
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    - sort_constructors_first
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - test_types_in_equals
    - valid_regexps
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - recursive_getters
    - unnecessary_overrides
    - unnecessary_this
    - use_string_buffers