name: flutter_fuse
description: A way to fuse the teams.

version: 0.8.7+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry: any

  cloud_firestore: "^0.12.9+3"
  firebase_auth: "^0.14.0+5"
  firebase_core: "^0.4.0+8"
  firebase_storage: "^3.0.6"
  firebase_analytics: "^5.0.1"
  firebase_performance: "^0.3.0+4"
  firebase_remote_config: "^0.2.0+5"
  firebase_messaging: "^5.1.5"
  flutter_bloc: ^0.21.0
  bloc: any
  shared_preferences: "^0.5.3+4"
  package_info: "^0.4.0"
  device_info: "^0.4.0"
  path_provider: "^1.3.0"
  uuid: any
  url_launcher: "^5.1.2"
  flutter_native_timezone: "^1.0.4"
    #path: ../../flutter_native_timezone
  flutter_places_dialog: "^1.0.5"
    #path: ../../flutter_places_dialog
  fusemodel:
    path: ../fusemodel
  sqflite: any
  badges: ^0.0.6

  fluro: any
  image_picker: "^0.6.1+4"
  timezone: ^0.5.4
  tuple: any
  sliver_calendar: ^0.2.0
    #path: ../../flutter_calendar
  #flutter_local_notifications:
   # path: ../../flutter_local_notifications
    #git:
    #  url: "git://github.com/pinkfish/flutter_local_notifications.git"

  cupertino_icons: ^0.1.2

  built_value: '>=6.7.0 <7.0.0'
  built_collection: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/images/banner.jpg
     - assets/images/abstractsport.png
     - assets/images/defaultavatar.png
     - assets/images/defaultavatar2.png
     - assets/timezone/2018c.tzf
     - assets/sports/Sport.Basketball.png
     - assets/sports/Sport.Soccer.png
     - assets/images/calendarbanner.jpg
     - assets/images/calendarheader.png
     - assets/images/leagueteam.png

  fonts:
    - family: CommunityIcons
      fonts:
          # https://materialdesignicons.com/
          - asset: assets/fonts/materialdesignicons-webfont.ttf