name: flutter_fuse
description: A way to fuse the teams.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry: any

  cloud_firestore: "^0.6.3"
  firebase_auth: "^0.5.7"
  firebase_core: "^0.2.2"
  firebase_storage: "^0.2.2"
  firebase_analytics: "^0.3.3"
  firebase_messaging: "^0.2.4"
  shared_preferences: "^0.3.3"
  package_info: "^0.3.0"
  device_info: "^0.2.0"
  path_provider: "^0.3.0"
  uuid: "^0.5.0"
  url_launcher: "^2.0.2"
  csv: "^3.1.2"
  flutter_native_timezone: # "^1.0.0"
    path: ../../flutter_native_timezone
  flutter_places_dialog: # "^1.0.0"
    path: ../../flutter_places_dialog

  fluro: any
  image_picker: "^0.4.1"
  timezone:
    path: ../../timezone
  fusemodel:
    path: ../../fusemodel
  sqflite: any
  tuple: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/images/banner.jpg
     - assets/images/abstractsport.png
     - assets/images/defaultavatar.png
     - assets/images/defaultavatar2.png
     - assets/timezone/2018c.tzf
     - assets/sports/Sport.Basketball.png
     - assets/sports/Sport.Soccer.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CommunityIcons
      fonts:
          # https://materialdesignicons.com/
          - asset: assets/fonts/materialdesignicons-webfont.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
