name: flutter_fuse
description: A way to fuse the teams.

version: 0.8.9
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  firebase_analytics: ^7.0.1
  firebase_performance: ^0.5.0+1
  firebase_crashlytics: ^0.4.0+1
  firebase_messaging:  ^8.0.0-dev.14
  cached_network_image: ^2.5.0
  charts_flutter:
    git:
      url: https://github.com/pinkfish/charts.git
      path: charts_flutter
  flutter_bloc: ^6.1.1
  flutter_svg: ^0.19.2+1
  video_player: ^1.0.1
  material_design_icons_flutter: ^4.0.5855
  bloc: ^6.1.1
  shared_preferences: ^0.5.12+4
  hydrated_bloc: ^6.1.0
  package_info: ^0.4.3+2
  device_info: ^1.0.0
  path_provider: ^1.6.27
  uuid: any
  url_launcher: ^5.7.10
  flutter_native_timezone: ^1.0.4
    #path: ../../flutter_native_timezone
  flutter_places_dialog: ^1.0.5
    #path: ../../flutter_places_dialog
  fusemodel:
    path: ../fusemodel
  sqflite: any
  badges: ^1.1.6
  universal_io: ^1.0.2

  fluro: any
  image_picker: ^0.6.7+22
  timezone: ^0.6.1
  tuple: any
  sliver_calendar: ^0.2.2
  flutter_cache_manager: ^2.1.1

  cupertino_icons: ^1.0.2

  built_value: '>=7.0.0 <8.1.0'
  built_collection: ^4.3.2

dependency_overrides:
  analyzer: ^0.41.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  intl_translation: ^0.17.10+1
  bloc_test: ^7.1.0
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.4
  build_runner: ^1.11.0
  built_value_generator: ^7.1.0


flutter:
  uses-material-design: true

  assets:
     - assets/images/banner.jpg
     - assets/images/abstractsport.png
     - assets/images/defaultavatar.png
     - assets/images/defaultavatar2.png
     - assets/timezone/2018c.tzf
     - assets/sports/Sport.Basketball.png
     - assets/sports/Sport.Soccer.png
     - assets/images/calendarbanner.jpg
     - assets/images/calendarheader.png
     - assets/images/leagueteam.png