name: flutter_fuse
description: A way to fuse the teams.
version: 0.9.20
homepage: http://www.teamsfuse.com
# Not publishing anywhere.
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ">=2.2.0 <3.0.0"
  firebase_auth: ">=3.1.3 <4.0.0"
  firebase_core: ">=1.7.0 <2.0.0"
  firebase_storage: ">=10.0.5 <11.0.0"
  firebase_analytics: ">=8.3.3 <9.0.0"
  firebase_performance: ">=0.7.1+1 <1.0.0"
  firebase_crashlytics: ">=2.2.3 <3.0.0"
  firebase_messaging: ">=10.0.8 <11.0.0"
  firebase_remote_config: ">=0.11.0 <1.0.0"
  firebase_dynamic_links: ">=2.0.10 <3.0.0"
  cached_network_image: ">=3.1.0 <4.0.0"
  charts_common:
    git:
      url: https://github.com/pinkfish/charts.git
      path: charts_common
  charts_flutter:
    git:
      url: https://github.com/pinkfish/charts.git
      path: charts_flutter
  flutter_bloc: ">=7.3.1 <8.0.0"
  flutter_svg: ">=0.22.0 <1.0.0"
  video_player: ">=2.1.3 <3.0.0"
  material_design_icons_flutter: ">=5.0.5955 <6.0.0"
  bloc: ">=7.0.0 <8.0.0"
  shared_preferences: ">=2.0.6 <3.0.0"
  hydrated_bloc: ">=7.0.0 <8.0.0"
  package_info: ">=2.0.1 <3.0.0"
  device_info: ">=2.0.1 <3.0.0"
  path_provider: ">=2.0.2 <3.0.0"
  uuid: any
  url_launcher: ">=6.0.2 <7.0.0"

  flutter_native_timezone: ">=2.0.0 <3.0.0"
  google_maps_flutter: ">=2.0.6 <3.0.0"
  geolocator: ">=7.7.0 <8.0.0"
  google_api_headers: ">=1.0.0 <2.0.0"
  fusemodel:
    path: ../fusemodel
  badges: ">=2.0.1 <3.0.0"
  universal_io: ">=2.0.4 <3.0.0"
  fluro: any
  image_picker: ">=0.8.1 <1.0.0"
  timezone: ">=0.8.0 <1.0.0"
  tuple: any
  sliver_calendar: ^0.4.2
  flutter_cache_manager: ">=3.0.2 <4.0.0"
  flutter_keyboard_visibility: ">=5.0.3 <6.0.0"
  flutter_local_notifications: ">=8.1.1 <9.0.0"

  cupertino_icons: ">=1.0.3 <2.0.0"

  built_value: ">=8.1.0 <8.4.0"
  built_collection: ">=5.0.0 <6.0.0"
  pedantic: ">=1.11.0 <2.0.0"
  exif: ">=3.0.0 <4.0.0"
  youtube_player_iframe: ">=2.1.0 <3.0.0"
  youtube_player_flutter: ">=8.0.0 <9.0.0"

dependency_overrides:
  analyzer: ^1.7.1
  intl: ^0.17.0
  petitparser: ^4.1.0
  intl_translation: ^0.17.10+1
  args: ^2.1.0
  dart_style: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  test: any
  mockito: ">=5.0.9 <6.0.0"
  golden_toolkit: ">=0.9.0 <1.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner.jpg
    - assets/images/abstractsport.png
    - assets/images/defaultavatar.png
    - assets/images/defaultavatar2.png
    - assets/timezone/2018c.tzf
    - assets/sports/Sport.Basketball.png
    - assets/sports/Sport.Soccer.png
    - assets/images/calendarbanner.jpg
    - assets/images/calendarheader.png
    - assets/images/leagueteam.png
    - assets/images/hands_and_trophy.png
    - assets/images/Basketball_Halfcourt.svg
    - assets/images/Basketball_Halfcourt_light.svg
    - assets/images/news-banner.png
