name: flutter_fuse
description: A way to fuse the teams.

version: 0.8.8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry: any

  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.0
  firebase_analytics: ^6.0.0
  firebase_performance: ^0.4.0
  firebase_remote_config: ^0.4.0
  firebase_messaging: ^7.0.0
  #flutter_crashlytics: any
  flutter_bloc: ^6.0.2
  hydrated_bloc: ^6.0.1
  bloc: any
  shared_preferences: ^0.5.10
  package_info: ^0.4.3
  device_info: ^0.4.2+7
  path_provider: ^1.6.14
  uuid: any
  url_launcher: ^5.5.0
  flutter_native_timezone: ^1.0.4
    #path: ../../flutter_native_timezone
  flutter_places_dialog: ^1.0.5
    #path: ../../flutter_places_dialog
  fusemodel:
    path: ../fusemodel
  sqflite: any
  badges: ^1.1.1

  fluro: any
  image_picker: ^0.6.7+7
  timezone: ^0.5.7
  tuple: any
  sliver_calendar: ^0.2.1
    #path: ../../flutter_calendar
  #flutter_local_notifications:
   # path: ../../flutter_local_notifications
    #git:
    #  url: "git://github.com/pinkfish/flutter_local_notifications.git"

  cupertino_icons: ^0.1.3

  built_value: '>=7.0.0 <7.2.0'
  built_collection: ^4.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/images/banner.jpg
     - assets/images/abstractsport.png
     - assets/images/defaultavatar.png
     - assets/images/defaultavatar2.png
     - assets/timezone/2018c.tzf
     - assets/sports/Sport.Basketball.png
     - assets/sports/Sport.Soccer.png
     - assets/images/calendarbanner.jpg
     - assets/images/calendarheader.png
     - assets/images/leagueteam.png

  fonts:
    - family: CommunityIcons
      fonts:
          # https://materialdesignicons.com/
          - asset: assets/fonts/materialdesignicons-webfont.ttf