version: "2"

services:
  firestore:
    image: perrystallings/cloud-firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=teamsfuse
  app:
    image: gcr.io/teamsfuse/firebase
    environment:
      - DATASTORE_EMULATOR_HOST=firestore
      - FIRESTORE_PROJECT_ID=teamsfuse