name: fusemodel
description: Model for the fused model.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  timezone:  any
  bloc: ^6.0.3
  equatable: ^1.2.5
  meta: any
  async: ^2.4.1
  built_value: '>=7.0.0 <7.2.0'
  built_collection: ^4.3.2
  hydrated_bloc: ^6.0.1
  path_provider: ^1.6.14
  hive: ^1.4.4

dev_dependencies:
  test: any
  mockito: any
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  effective_dart: ^1.2.4

  flutter_test:
    sdk: flutter
