name: fusemodel
description: Model for the fused model.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  timezone:  any
  bloc: ^6.1.1
  equatable: ^1.2.5
  meta: any
  async: ^2.4.2
  built_value: '^8.0.0-nullsafety.0'
  built_collection: ^5.0.0-nullsafety
  hydrated_bloc: ^6.1.0
  path_provider: ^1.6.27
  hive: ^1.4.4+1

dev_dependencies:
  test: any
  mockito: any
  build_runner: ^1.11.0
  built_value_generator: ^8.0.0-nullsafety.0
  effective_dart: ^1.3.0

  flutter_test:
    sdk: flutter
