name: fusemodel
description: A new flutter package project.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  timezone:  any
  bloc: ^3.0.0
  equatable: ^1.0.3
  meta: any
  async: ^2.4.0
  built_value: '>=6.7.0 <7.0.0'
  built_collection: ^4.3.2

dev_dependencies:
  test: any
  mockito: any
  build_runner: ^1.0.0
  built_value_generator: ^6.3.2
