name: fusemodel
description: A new flutter package project.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  timezone:  ^0.5.2

dev_dependencies:
  test: any
