name: fusemodel
description: A new flutter package project.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  timezone:
     git:
       url: "https://github.com/pinkfish/timezone.git"

dev_dependencies:
  test: ^0.12.30
