name: fusemodel
description: A new flutter package project.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  timezone:  any
  bloc: any
  equatable: any
  meta: any
  async: ^2.1.0

dev_dependencies:
  test: any
  mockito: any
