name: fusemodel
description: Model for the fused model.
version: 0.0.1
author: David Bennett <pinkfishfrog@gmail.com>
homepage: http://www.whelksoft.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  timezone: ^0.7.0-nullsafety.0
  bloc: ^6.1.3
  equatable: ^2.0.0
  meta: ^1.3.0
  async: ^2.5.0
  built_value: ^8.0.0
  built_collection: ^5.0.0
  hive: ^2.0.0
  clock: ^1.1.0

dependency_overrides:
  analyzer: ^0.41.2

dev_dependencies:
  test: any
  mockito: any
  build_runner: ^1.11.5
  built_value_generator: ^8.0.0
  pedantic: ^1.11.0
