name: teamfuse
description: A web app that uses AngularDart with lots of fun
version: 0.0.1
publish_to: none

environment:
  sdk: ">=1.9.0 <3.0.0"

dependencies:
  angular_components: ^1.0.2
  firebase: ^8.0.0
  pwa: ^0.2.0
  angular: ^6.0.1
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  csv: ^4.1.0
  google_maps: ">=3.0.0 <4.0.0"
  googleapis_auth: ^0.2.12+1
  timezone: any
  service_worker: any
  angular_bloc: any
  fusemodel:
    path: ../../fusemodel

dependency_overrides:
  built_collection: ^5.0.0-nullsafety
  fixnum: ^1.0.0-nullsafety

dev_dependencies:
  sass_builder: ^2.1.3
  angular_test: ^3.0.0
  build_runner: ^1.11.0
  build_test: ^1.3.4
  build_web_compilers: ^2.16.1
  test: ^1.15.7
  pedantic: ^1.11.0
