steps:
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase/functions'
    args: [ 'npm', 'update' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase'
    args: [ 'ls' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase'
    args: [ 'bash', '/workspace/firebase/firebase-emulator.sh', 'start' ]
  #  - name: 'gcr.io/teamsfuse/firebasenode'
  #    dir: 'firebase'
  #    args: [ 'firebase', 'serve', '--only', 'firestore', '--port=9090', '--host=0.0.0.0' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase/functions'
    args: [ 'npm', 'test' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase'
    args: [ 'bash', '/workspace/firebase/firebase-emulator.sh', 'stop' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    args: ['firebase', 'use', '--token', '$_FIREBASE_DEPLOY_KEY', 'production' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    args: ['firebase', 'use', '--add', 'teamsfuse', 'production' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    args: ['firebase', 'deploy', '--non-interactive', '--token', '$_FIREBASE_DEPLOY_KEY', '--only', 'functions,firestore,storage']
