# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build_number = number_of_commits(all: true)
    changelog_from_git_commits
    gradle(task: "assembleRelease")


    firebase_app_distribution(
              apk_path: '../build/app/outputs/apk/release/app-release.apk',
              app: "1:400199897683:android:5433fb56c222e6e8",
              testers: "pinkfishfrog@gmail.com",
              release_notes: "Lots of amazing new features to test out!",
              firebase_cli_path: "/Users/david/.nvm/versions/node/v12.9.1/bin/firebase"
   )
    #upload_to_play_store(
    #   track: 'beta',
    #)
    #crashlytics(
   # #    api_token: '8e49e324965658b5d6497544fb73022fbf38e28f',
  #      build_secret: '400dd35eaffac89c5c40c740eb0c58950ac5bacec99c34ad13df30b8a0f26051',
  #      apk_path: '../build/app/outputs/apk/release/app-release.apk'
  #  )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
