# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    project = 'Runner.xcodeproj'

    version = get_version_number(xcodeproj: project,)
    desc "Version $version"
    #build_number = app_store_build_number(
    #  app_identifier: 'com.teamfuse.flutterfuse',
    #  username: 'pinkfishfrog@gmail.com',
    #  live: false
    #)
    build_number = latest_testflight_build_number(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      version: version,
      initial_build_number: 30
    )
    increment_build_number(
      build_number: build_number + 1,
      xcodeproj: project
    )
    match(type: "appstore", readonly: is_ci)
    #get_certificates           # invokes cert
    #get_provisioning_profile   # invokes sigh
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end

  lane :release do
    sync_code_signing
    disable_automatic_code_signing(path: "my_project.xcodeproj")
    build_app
    enable_automatic_code_signing(path: "my_project.xcodeproj")
    upload_to_testflight
  end
end

