steps:
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase/functions'
    args: [ 'npm', 'update' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase'
    args: [ 'firebase', 'serve', '--only', 'firestore' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    dir: 'firebase/functions'
    args: [ 'npm', 'test' ]
  - name: 'gcr.io/teamsfuse/firebasenode'
    args: ['firebase', 'deploy --token="1/AbUh26_WYBfWEJJLlJaXXCGwTRFGChXTRh_tvRWQTD0LQp8QLs0D36IInl9U6euQ" --only functions,firestore,storage']
