name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    paths:
      - "flutter_fuse/**"
      - "public_ux/**"
      - "fusemodel/**"
      - "firebase/**"
      - ".github/workflows/firebase-hosting-pull-request.yml"
    branches:
      - main
  push:
    paths:
      - "flutter_fuse/**"
      - "public_ux/**"
      - "fusemodel/**"
      - "firebase/**"
      - ".github/workflows/firebase-hosting-pull-request.yml"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta" # or: 'dev' or 'beta'
      - run: flutter pub get
        working-directory: fusemodel
      - run: |
          find ./ -type f -name "*.g.dart" -delete
          flutter clean
          flutter pub get
          flutter pub run build_runner build
        working-directory: fusemodel
      - run: flutter packages get
        working-directory: flutter_fuse
      - run: flutter config --enable-web
        working-directory: flutter_fuse
      - run: sudo apt-get install -y graphicsmagick
        working-directory: flutter_fuse
      - run: |
          echo final String googleMapsApiKey = \"${{ secrets.GOOGLE_MAPS_WEB }}\"\; > apikeys.dart
        working-directory: flutter_fuse/lib/services
      - run: flutter test
        working-directory: flutter_fuse
      - run: |
          flutter build web
          mkdir -p ../firebase/public/flutter
          cp -fR build/web/* ../firebase/public/flutter
        working-directory: public_ux
      - run: |
          flutter build web
          mkdir -p ../firebase/public/flutter/main
          cp -fR build/web/* ../firebase/public/flutter/main
        working-directory: flutter_fuse

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEAMSFUSE }}"
          projectId: teamsfuse
          entryPoint: firebase
          channelId: alpha
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
