name: Firebase functions

# Update when the functions change or this changes.
on:
  push:
    branches: [main]
    paths:
      - "firebase/functions/**"
      - ".github/workflows/firebase-functions.yml"
  pull_request:
    branches: [main]
    paths:
      - "firebase/functions/**"
      - ".github/workflows/firebase-functions.yml"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            ~/.cache/firebase/emulators
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: |
          npm install
        working-directory: firebase/functions
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build
        run: npm run build
        working-directory: firebase/functions
      - name: Setup and test emulator
        run: |
          export PATH=$PATH:/usr/local/bin
          npm install grpc --verbose
          sudo npm install -g firebase-tools
          npm run test
        working-directory: firebase/functions
        env:
          FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
          PROJECT_PATH: firebase
          PROJECT_ID: teamsfuse
      - name: Deploy to Firebase
        run: |
          firebase use --add teamsfuse
          npm run deployci
        working-directory: firebase/functions
        env:
          FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
          PROJECT_PATH: firebase
          PROJECT_ID: teamsfuse
