name: Flutter - ios

on: 
  release:
    types: [created,edited]

jobs:
  build:
   runs-on: macos-latest

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Dump env
      run: |
        echo ${SOURCE_TAG}
        echo ${SOURCE_BRANCH}
        echo ${SOURCE_TAG}
        echo ${{ GITHUB.ref }}
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: fusemodel
    - run: flutter pub run build_runner build
      working-directory: fusemodel
    - run: flutter packages get
      working-directory: flutter_fuse
    - run: flutter test
      working-directory: flutter_fuse
    - run: brew install graphicsmagick
      working-directory: flutter_fuse
    #- run: echo ${GOOGLESERVICES} > ios/Runner/GoogleService-Info.plist
      #working-directory: flutter_fuse
      #env: 	
        #GOOGLESERVICES: ${{ secrets.googleservicesIos }}
    - run: echo ${APPLE_APP_API_P8} > ~/apple-app-api.p8
      working-directory: flutter_fuse/ios
      env: 	
        APPLE_APP_API_P8: ${{ secrets.APPLE_APP_API_P8 }}
    - run:   echo $(PASSWORD) > fastlane/metadata/review_information/test_password.txt
      working-directory: flutter_fuse/ios
      env:
        PASSEORD: ${{ secrets.TEST_USER_PASSWORD }}
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: beta
        subdirectory: flutter_fuse/ios
        bundle-install-path: ux/ios/packages
        options: '{"version": "${{ steps.branch_name.outputs.SOURCE_TAG }}"}'
      env:
        FASTLANE_SESSION: ${{ secrets.FASTLANE_APPLE_SESSION }}
        FL_GITHUB_RELEASE_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 10 # Longer timeout for the build settings.
        APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
        DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
        DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
        FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
        MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
        TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
        TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/ios/iphoneos/*.app"
        token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Release notes for the ios ${{ steps.branch_name.outputs.SOURCE_TAG}} version" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUBPUSHTOKEN }}
        branch: main
        force: true

