name: Flutter - web

on:
  release:
    types: [created,edited]

  push:
    branches: [main]
    paths:
      - .github/workflows/flutter-web.yml

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: fusemodel 
    - run: flutter pub run build_runner build
      working-directory: fusemodel
    - run: flutter packages get
      working-directory: flutter_fuse
    - run: flutter config --enable-web
      working-directory: flutter_fuse
    - run: sudo apt-get install -y graphicsmagick
      working-directory: flutter_fuse
    - run: flutter test
      working-directory: flutter_fuse
    - run: flutter build web
      working-directory: flutter_fuse
    - run: |
        mkdir -p firebase/public/flutter
        cp -fR flutter_fuse/build/web/* firebase/public/flutter
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASETOKEN }}
        FIREBASE_PROJECT: teamsfuse
        PROJECT_PATH: ./firebase
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Release notes for the ios ${{ steps.branch_name.outputs.SOURCE_TAG}} version" -a
