name: Flutter - android - firebase

on: 
  push:
    paths:
    - 'flutter_fuse/**'
    - 'fusemodel/**'
    - '.github/workflows/flutter-android-firebase.yml'
  pull_request:
    paths:
    - 'flutter_fuse/**'
    - 'fusemodel/**'
    - '.github/workflows/flutter-android-firebase.yml'
    
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    - name: Branch name
      id: branch_name
      run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Dump env
      run: |
          echo ${SOURCE_TAG} 
          echo ${SOURCE_BRANCH}
          echo ${SOURCE_TAG}
          echo ${{ GITHUB.ref }}
      env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Setup firebase tools
      run: |
        export PATH=$PATH:/usr/local/bin
        npm install grpc --verbose
        sudo npm install -g firebase-tools
      working-directory: firebase/functions
    - run: flutter pub get
      working-directory: fusemodel
    - run: |
        find ./ -type f -name "*.g.dart" -delete
        flutter clean
        flutter pub get
        flutter packages pub run build_runner build --delete-conflicting-outputs
      working-directory: fusemodel
    - run: flutter packages get
      working-directory: flutter_fuse
    - run: flutter test
      working-directory: flutter_fuse
    - run: sudo apt-get install -y graphicsmagick
      working-directory: flutter_fuse
    - run: echo ${FASTLANE_ANDROID_API_KEY} > ./api-dash.json	
      working-directory: flutter_fuse/android
      env: 	
        FASTLANE_ANDROID_API_KEY: ${{ secrets.FASTLANE_ANDROID_API_KEY }}
    - run: echo ${ANDROID_KEY_JKS} > ./key.jks.asc
      working-directory: flutter_fuse/android
      env: 	
        ANDROID_KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
    - run: base64 --decode < ./key.jks.asc > key.jks 
      working-directory: flutter_fuse/android
    - run: flutter build  appbundle
      working-directory: flutter_fuse/android
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: firebase
        subdirectory: flutter_fuse/android
        options: '{"version": "${{ steps.branch_name.outputs.SOURCE_TAG }}"}'
      env:
        FL_GITHUB_RELEASE_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASETOKEN }}
